name: Build and Publish PowerShell Containers

on:
  push:
    branches:
      - main
      - ci
    paths:
      - build.ps1
      - .github/workflows/build-and-publish.yml
  workflow_dispatch:
    inputs:
      imageName:
        description: 'Container image name (e.g. powershell-test)'
        required: true
        default: 'powershell-test'
      specificVersions:
        description: 'PowerShell versions to build (comma-separated, e.g. 7.2.6,7.3.4)'
        required: false
        default: ''
      clobber:
        description: 'Overwrite existing remote images in the registry. Use with caution as this will force a rebuild and push of all specified versions.'
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: ${{ (inputs.imageName == 'powershell' || github.ref_name == 'main') && 'Github Container Registry' || 'Github Container Registry - Test' }}
    env:
      ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install Podman
      run: |
        sudo pwsh -f .github/workflows/Update-Podman.ps1

    - name: Get lowercase repository owner
      id: repo_owner
      run: echo "repo_owner_lower=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry with Podman
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io/${{ env.repo_owner_lower }}
        username: ${{ env.repo_owner_lower }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Breakpoint if debug retry
      if: ${{ env.ACTIONS_STEP_DEBUG == 'true' }}
      uses: namespacelabs/breakpoint-action@v0
      with:
        duration: 30m
        authorized-users: justingrote
        authorized-keys: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA7rgymJb1ra+772/X9XDK3OOMiPlYx/NWKZIbOx+tFa

    - name: Build and publish containers
      shell: pwsh
      run: |
        # The login step above doesn't seem to persist for some reason, so re-login here
        podman login ghcr.io/${{ env.repo_owner_lower }}
        $splat = @{}

        #We need to handle if no inputs were provided, for example during a push
        if ('${{ inputs.specificVersions }}' -ne '') {
          $splat['Versions'] = '${{ inputs.specificVersions }}' -split ',' | ForEach-Object Trim
        }

        $imageName = '${{ inputs.imageName }}'
        if ('${{ inputs.imageName }}' -eq '') {
          if ($env:GITHUB_REF_NAME -eq 'main') {
            $imageName = 'powershell'
          } else {
            $imageName = 'powershell-test'
          }
        }

        # $splat['Push'] = '${{ inputs.push }}' -eq 'true' ? $true : $false
        $splat['Push'] = $true
        $splat['Clobber'] = '${{ inputs.clobber }}' -eq 'true' ? $true : $false

        ./build.ps1 -Verbose -RemoteImageName "ghcr.io/${{ env.repo_owner_lower }}/$imageName" @splat

    - name: List built images
      run: podman images --filter reference=powershell --format "table {{.Repository}}:{{.Tag}} {{.Size}} {{.Created}}"
